import Foundation
import AppKit

/// The macOS stand-in for `CClip::LoadFromClipboard` and `COleClipSource`.
///
/// Windows Ditto reads and writes HGLOBAL blocks keyed by CLIPFORMAT; here the
/// same job is reading and writing `NSPasteboard` types. Everything is
/// converted to the Windows byte layout on the way in and back on the way out,
/// so `Data.ooData` means the same thing on both platforms.
enum PasteboardBridge {

    /// The "please don't record this" markers macOS clipboard tools agree on.
    /// The nearest Windows equivalent is Ditto's own `Clipboard Viewer Ignore`
    /// format, which is also honoured here.
    static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("Clipboard Viewer Ignore"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        guard Options.shared.honourConcealedPasteboardTypes else { return false }
        guard let types = pasteboard.types else { return false }
        for concealed in concealedTypes where types.contains(concealed) {
            Log.write("skipping clip marked \(concealed.rawValue)")
            return true
        }
        return false
    }

    // MARK: - Reading

    /// Read every enabled format off the pasteboard, in the order Ditto stores
    /// them: richest first, so `SetDescFromType` picks a sensible description.
    static func read(from pasteboard: NSPasteboard,
                     enabledFormats: Set<String>) -> [ClipFormatData] {
        var formats: [ClipFormatData] = []
        guard let types = pasteboard.types else { return formats }

        func has(_ type: NSPasteboard.PasteboardType) -> Bool {
            return types.contains(type)
        }

        // Files ------------------------------------------------------------
        if enabledFormats.contains(ClipFormat.fileDrop) {
            let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
            if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                                 options: options) as? [URL],
               urls.isEmpty == false {
                let paths = urls.map { $0.path }
                formats.append(ClipFormatData(ClipFormat.fileDrop,
                                              ClipFormat.encodeFileDrop(paths)))
            }
        }

        // Images -----------------------------------------------------------
        var pngBytes: Data?
        if has(.png) {
            pngBytes = pasteboard.data(forType: .png)
        } else if has(.tiff), let tiff = pasteboard.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: tiff) {
            pngBytes = rep.representation(using: .png, properties: [:])
        }
        if let png = pngBytes, png.isEmpty == false {
            if enabledFormats.contains(ClipFormat.png) {
                formats.append(ClipFormatData(ClipFormat.png, png))
            }
            // Also store a DIB so the clip pastes into Windows apps if the
            // database is shared. Skipped for very large images: the DIB is
            // uncompressed and would double the row for little gain.
            if enabledFormats.contains(ClipFormat.dib), png.count < 4 * 1024 * 1024,
               let dib = BitmapHelper.dib(fromPNG: png) {
                formats.append(ClipFormatData(ClipFormat.dib, dib))
            }
        }

        // Rich text --------------------------------------------------------
        if enabledFormats.contains(ClipFormat.richText), has(.rtf),
           let rtf = pasteboard.data(forType: .rtf), rtf.isEmpty == false {
            formats.append(ClipFormatData(ClipFormat.richText, ClipFormat.encodeRTF(rtf)))
        }

        // HTML -------------------------------------------------------------
        if enabledFormats.contains(ClipFormat.html), has(.html),
           let htmlData = pasteboard.data(forType: .html),
           let html = String(data: htmlData, encoding: .utf8), html.isEmpty == false {
            formats.append(ClipFormatData(ClipFormat.html, ClipFormat.encodeHTML(html)))
        }

        // URL --------------------------------------------------------------
        if enabledFormats.contains(ClipFormat.fileURL), has(.URL),
           let url = pasteboard.string(forType: .URL), url.isEmpty == false,
           url.hasPrefix("file://") == false {
            formats.append(ClipFormatData(ClipFormat.fileURL,
                                          ClipFormat.encodeUnicodeText(url)))
        }

        // Text -------------------------------------------------------------
        var text = pasteboard.string(forType: .string)
        if text == nil, let rtfData = pasteboard.data(forType: .rtf),
           let attributed = NSAttributedString(rtf: rtfData, documentAttributes: nil) {
            text = attributed.string
        }
        if let text = text, text.isEmpty == false {
            if enabledFormats.contains(ClipFormat.unicodeText) {
                formats.append(ClipFormatData(ClipFormat.unicodeText,
                                              ClipFormat.encodeUnicodeText(text)))
            }
            if enabledFormats.contains(ClipFormat.text) {
                formats.append(ClipFormatData(ClipFormat.text, ClipFormat.encodeText(text)))
            }
        }

        return formats
    }

    // MARK: - Writing

    /// Put a clip's formats onto a pasteboard. `plainTextOnly` is the
    /// PASTE_SELECTED_PLAIN_TEXT action - drop everything but the text.
    @discardableResult
    static func write(_ formats: [ClipFormatData],
                      to pasteboard: NSPasteboard,
                      plainTextOnly: Bool = false) -> Bool {
        let item = NSPasteboardItem()
        var wroteSomething = false
        var fileURLs: [URL] = []

        for format in formats {
            switch format.format {
            case ClipFormat.unicodeText:
                let text = ClipFormat.decodeUnicodeText(format.bytes)
                if text.isEmpty == false {
                    item.setString(text, forType: .string)
                    wroteSomething = true
                }

            case ClipFormat.text:
                // Only used when there was no unicode text to begin with.
                if item.string(forType: .string) == nil {
                    let text = ClipFormat.decodeText(format.bytes)
                    if text.isEmpty == false {
                        item.setString(text, forType: .string)
                        wroteSomething = true
                    }
                }

            case ClipFormat.richText:
                if plainTextOnly { continue }
                let rtf = ClipFormat.decodeRTF(format.bytes)
                if rtf.isEmpty == false {
                    item.setData(rtf, forType: .rtf)
                    wroteSomething = true
                }

            case ClipFormat.html:
                if plainTextOnly { continue }
                let html = ClipFormat.decodeHTML(format.bytes)
                if html.isEmpty == false {
                    item.setString(html, forType: .html)
                    wroteSomething = true
                }

            case ClipFormat.png:
                if plainTextOnly { continue }
                if format.bytes.isEmpty == false {
                    item.setData(format.bytes, forType: .png)
                    if let rep = NSBitmapImageRep(data: format.bytes),
                       let tiff = rep.representation(using: .tiff, properties: [:]) {
                        item.setData(tiff, forType: .tiff)
                    }
                    wroteSomething = true
                }

            case ClipFormat.dib:
                if plainTextOnly { continue }
                // Only fall back to the DIB when the clip carries no PNG,
                // which is the case for clips written by Windows Ditto.
                if item.data(forType: .png) == nil,
                   let image = BitmapHelper.image(fromDIB: format.bytes),
                   let png = BitmapHelper.pngData(from: image) {
                    item.setData(png, forType: .png)
                    if let tiff = image.tiffRepresentation {
                        item.setData(tiff, forType: .tiff)
                    }
                    wroteSomething = true
                }

            case ClipFormat.fileDrop:
                if plainTextOnly { continue }
                let paths = ClipFormat.decodeFileDrop(format.bytes)
                fileURLs = ClipFormat.localFileURLs(from: paths)
                if fileURLs.isEmpty && paths.isEmpty == false && item.string(forType: .string) == nil {
                    // The files came from another machine - paste their names.
                    item.setString(paths.joined(separator: "\n"), forType: .string)
                    wroteSomething = true
                }

            case ClipFormat.fileURL:
                if plainTextOnly { continue }
                let url = ClipFormat.decodeUnicodeText(format.bytes)
                if url.isEmpty == false {
                    item.setString(url, forType: .URL)
                    if item.string(forType: .string) == nil {
                        item.setString(url, forType: .string)
                    }
                    wroteSomething = true
                }

            default:
                continue
            }
        }

        pasteboard.clearContents()

        var objects: [NSPasteboardWriting] = []
        if wroteSomething { objects.append(item) }
        for url in fileURLs {
            objects.append(url as NSURL)
        }

        guard objects.isEmpty == false else { return false }
        return pasteboard.writeObjects(objects)
    }

    /// Write one plain string, for the "paste as ..." transforms.
    static func write(text: String, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // MARK: - Save and restore

    /// A snapshot of the current pasteboard, so a paste can put things back
    /// afterwards. Ditto does the same in `ClipboardSaveRestore.cpp`.
    struct Snapshot {
        var items: [[NSPasteboard.PasteboardType: Data]]
    }

    static func snapshot(_ pasteboard: NSPasteboard = .general) -> Snapshot {
        var saved: [[NSPasteboard.PasteboardType: Data]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    entry[type] = data
                }
            }
            if entry.isEmpty == false { saved.append(entry) }
        }
        return Snapshot(items: saved)
    }

    static func restore(_ snapshot: Snapshot, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        guard snapshot.items.isEmpty == false else { return }
        var objects: [NSPasteboardWriting] = []
        for entry in snapshot.items {
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            objects.append(item)
        }
        pasteboard.writeObjects(objects)
    }
}
